name: package_info_plus_example
description: Demonstrates how to use the package_info_plus plugin.
version: 1.2.3+4
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  package_info_plus:
    path: ../

dependency_overrides:
  package_info_plus_platform_interface:
    path: ../../package_info_plus_platform_interface

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
