name: network_info_plus
description: Flutter plugin for discovering information (e.g. WiFi details) of the network.
version: 3.0.1
homepage: https://plus.fluttercommunity.dev/
repository: https://github.com/fluttercommunity/plus_plugins/tree/main/packages/network_info_plus
issue_tracker: https://github.com/fluttercommunity/plus_plugins/labels/network_info_plus

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.11.0"

flutter:
  plugin:
    platforms:
      android:
        package: dev.fluttercommunity.plus.network_info
        pluginClass: NetworkInfoPlusPlugin
      ios:
        pluginClass: FLTNetworkInfoPlusPlugin
      linux:
        dartPluginClass: NetworkInfoPlusLinuxPlugin
      macos:
        pluginClass: NetworkInfoPlusPlugin
      windows:
        pluginClass: NetworkInfoPlusWindowsPlugin
      web:
        pluginClass: NetworkInfoPlusWebPlugin
        fileName: src/network_info_plus_web.dart

dependencies:
  collection: ^1.15.0
  nm: ^0.5.0
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  meta: ^1.8.0
  network_info_plus_platform_interface: ^1.1.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.3.2
  plugin_platform_interface: ^2.1.3
  flutter_lints: ^2.0.1
